<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="UTF-8"%>
<%@ page import="java.sql.*" %>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-compatible" content="IE=edge">
<meta name="viewpoint" content="width=device-width,initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<title>Home Page</title>
</head>
<style> 
   body{
	  background-image: url('https://th.bing.com/th/id/OIP.lxzY_r8MdCqEfFSduvfOqAHaEo?w=297&h=185&c=7&r=0&o=5&dpr=1.25&pid=1.7');
      background-repeat: no-repeat;
      background-size: cover;
}
    .box{
        border: 1px solid whitesmoke;
        background-color: whitesmoke;
        height: 55px;
       
    }
    ol a  {
        float: left;
        left: 40%;
        position: relative;
        font-size: 20px;
        list-style-type: none;
        font-size: 30px;
       padding:10px;
        color: black;
        padding-bottom: 10px;
        font-family: Arial, Helvetica, sans-serif;
        text-decoration: none;
     }
    .cover img{
        width: 100%;
        height: 560px;
        top: 0;
    }
    .text{
        position: absolute;
        top: 40%;
        left: 20%;
    }
    h1{
        font-size: 80px;
        font-family: barlow condensed,sans-serif;
        text-transform: capitalize;
        width: 460px;
        word-spacing: 0px;
        font-weight: normal;
        line-height: 82px;
        
    }
    h4{
       position: absolute;  
        font-size: 18px;
        font-family: barlow condensed,sans-serif;  
        text-transform: uppercase; 
    }
    .description-container{
        max-width: 100%;
        margin-top: 20px;

    }
    .description-container .floating-image{
        max-width: 400px;
    }
    .description-container .floating-image.right{
        float:right;
        margin-left: 30px;
        margin-bottom: 10px;
        margin-top: 20px;
    }
    .description-container .floating-image.left{
        float: left;
        margin-right: 30px;
        margin-bottom: 10px;
    }
</style>
<body>
<%String password=request.getParameter("password");
String email=request.getParameter("email"); %>
 <div class="box sticky-top">
<ol>
<a>E-Authentication System </a>
		   </ol>
		   </div>
		   <div class="container">
		       <div class="description-container">
		           
		           <h3>About Application</h3>
		           <p>
		            In the proposed scheme, the user can easily and efficiently login into the system. 
		            We analyze the security and usability of the proposed scheme, and show the resistance of the proposed scheme to hacking of login credentials, shoulder surfing and accidental login. 
		            The shoulder surfing attack can be performed by the adversary to obtain the user’s password by watching over the user’s shoulder as he enters his password. 
		            Since, we have come up with a secure system schemes with different degrees of resistance to shoulder surfing have been proposed. 
		            In order to use this authentication system, user need to first register himself into this system by filing up the basic registration details. 
		            After a successful registration, user can access the login module where he/she need to first authenticate the account by entering the email id and password which was entered while registration. 
		            Once the email id and password is authenticated, the user may proceed with next authentication section where he/she need to select the type of authentication as QR (Quick Response) Code or OTP (One Time Password). 
		            Once the user selects the authentication type as QR Code, then system will generate a QR Code and send it to user’s mail id over internet. 
		            If user select’s OTP, then SMS will be sent on his/her registered mobile number. 
		            If the user passes the authentication, then system will redirect to the main page. 
		            The QR Code and OTP are randomly generated by the system at the time of login.  
		           </p>
		           <br>
		           <img src="https://www.image-illustration.net/wp-content/uploads/2018/06/identity-authentication-concept.jpg" alt="" class="img-responsive floating-image right" style="width: 500px;">
		           <p><br>
		            <h5>Existing System ::</h5> 
		            In A Secure Mobile Payment System using QR Code paper, the authors proposed a state of affairs for mobile payment that tackles each considerations of the method, namely: speed of group action and security, while not complicating the method or creating it undesirable to users.
                    In the paper QR-TAN: Secure Mobile Transaction Authentication, the authors contributed with the QR-TAN authentication technique. QR-tans area unit a dealing authentication technique supported two-dimensional barcodes. Compared to different established techniques, 
                    QR-tans show 3 advantages: initial, QR-tans enable the user to directly validate The content of a dealing among a sure device. 
                    Second,validation is secure notwithstanding associate offender manages to achieve full management over a users laptop. Finally, QR-tans together with sensible cards may also be utilised for offline transactions that do not need any server
                    In the system Advanced Online Banking Authentication System Using One Time Passwords Embedded in Q-R Code, the authors explained implementation details of on-line banking authentication system. 
                    Security is associate vital issue for on-line banking application which might be enforced by varied web technologies. 
                    Whereas implementing on-line banking system, secure information transfer want is consummated by exploitation https information transfer and info encryption techniques for secure storage of sensitive info. 
                    To eliminate threat of phishing and to substantiate user identity we have a tendency to ar aiming to use conception of QR-code with robot application. 
                    QR-code which might be scanned by user mobile device that overcome the weakness of ancient countersign based mostly system. We have a tendency to improvemore security by exploitation only once countersign (OTP) that hides within QR- code
		            <img src="https://th.bing.com/th/id/OIP.NqD_oQokNKnYPdoZ9Uo-lwHaE2?w=258&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7" alt="" class="img-responsive floating-image right" style="width: 400px;">     
		            <br><br>       
		            <h5>Advantages of System ::</h5>
		            Helps users to login into their account more securely.<br>
                    Hackers won not be able to collect the password via shoulder surfing.<br>
                    Complex password technique with easy user interface.<br>
                    Two way authentication is done, so it is more secure and not vulnerable to any kind of attacks.<br>
<br><br>
		            
		   
		          
</p>		           
</div>
</div>
</div> 
  
</body>
</body>
</html>
